### ISSUE TITLE
Define pairs available in each chain (JSON / TS)

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#39]
Depending on the current user chain, available token for borrow will change.

At first we think with @brozorec of a simple config file like this:
```yaml
chainA:
  - collateral: ETH, USDC
  - borrow: USDC, FTM
chainB:
  - collateral: FTM, USDC
  - borrow: WETH, OP
```

But this won't be enough, so we need to rethink the logic on how to know available tokens to borrow.

Basically, the goal of this is to write the business logic, that can be represented with a function like this

```ts
type getBorrowableTokens = (from: Chain, to: Chain) => Token[] 
```
